name: Deploy to Laravel Forge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Trigger Forge Deployment
        run: curl -X POST https://forge.laravel.com/servers/301103/sites/2635918/deploy/http?token=${{ secrets.FORGE_DEPLOY_TOKEN }}
