name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main  # Change to your deploy branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install --frozen-lockfile

      - name: Build the project
        run: npm run build

      - name: Upload Build Files to Server
        env:
          HOST: ${{ vars.DO_SERVER_IP}}
          USER: ${{ vars.DO_SSH_USER }}
          SSH_KEY: ${{ secrets.DO_SSH_KEY }}
        run: |
          echo "$SSH_KEY" > private_key && chmod 600 private_key
          rsync -avz -e "ssh -i private_key" ./dist/ $USER@$HOST:/home/forge/it.ai/
          rm private_key
